# Generated by Django 5.0.5 on 2024-05-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('said_by', models.CharField(max_length=200)),
                ('quote', models.CharField(max_length=500)),
                ('anime', models.CharField(max_length=200)),
            ],
        ),
    ]
